'use strict';

// Package entry point. T02-T05 exported the native binding's surface
// directly (hello, napiVersion, version, versionNumber, capabilities,
// cameraCount, cameraList, buildInfo, decodeSync). T06 adds the Processor
// object API and its error model on top, without changing any of that
// existing surface:
//   - lib/binding.cjs resolves and loads the native addon (node-gyp-build).
//   - lib/errors.cjs defines LibRawError, the class Processor methods throw.
//   - lib/processor.cjs wraps the native Processor class (binding.Processor)
//     so its thrown Napi::Errors become LibRawError instances.
// T08 adds the fused, stateless helpers (decode, identify, thumbnail --
// src/fused.cc/.h) the same way: lib/fused.cjs wraps them so their
// rejections become LibRawError instances too.
const native = require('./binding.cjs');
const { LibRawError } = require('./errors.cjs');
const { wrapProcessor } = require('./processor.cjs');
const { wrapFused, FUSED_METHODS } = require('./fused.cjs');
// T10: LibRaw_progress code <-> short-name tables (scripts/gen-progress.js),
// exported as `progressStages` (name -> numeric LibRaw_progress code) so a
// caller can compare a `progress` event's `stage` string against it, or
// look up LibRaw's own numeric constant, without needing the raw enum.
const { NAME_TO_STAGE } = require('./generated/libraw-progress.cjs');
// T13: every enum in libraw_const.h (scripts/gen-enums.js), exported as
// `enums` -- see this file's `enums` assignment below for the exact shape
// and README.md's "Enums and flags" section for the documented scheme.
const { ENUMS, namesForMask } = require('./generated/libraw-enums.cjs');

const Processor = wrapProcessor(native.Processor, LibRawError);
const fused = wrapFused(native, LibRawError);

// T13: `enums` exposes every enum in libraw_const.h (api/enums.json /
// lib/generated/libraw-enums.cjs, both generated by scripts/gen-enums.js).
// `enums.all[cEnumName]` has the full manifest by its C type name (e.g.
// `enums.all.LibRaw_processing_options`); `ENUM_ALIASES` below adds short,
// documented aliases (`enums.WARN`, `enums.CAPS`, ...) for the families
// callers reach for most often -- picking this "object of named enum
// tables" scheme (docs/plan/tasks.md T13: "pick one scheme and document it
// in README.md") over flattening every family into its own top-level named
// export, so the alias list can grow without widening the package's own
// export surface. Each entry is `{ kind: 'flags' | 'enum', NAME_TO_VALUE
// (short name -> value), VALUE_TO_NAME (value -> first short name, e.g. for
// `enums.WARN.NAME_TO_VALUE.FALLBACK_TO_AHD`), VALUE_TO_NAMES (value -> all
// short names sharing it, only relevant for LibRaw_decoder_flags' 3CHANNEL/
// SINAR4SHOT collision) }`.
const ENUM_ALIASES = {
  WARN: 'LibRaw_warnings',
  CAPS: 'LibRaw_runtime_capabilities',
  DECODER: 'LibRaw_decoder_flags',
  RAWOPTIONS: 'LibRaw_processing_options',
  PROGRESS: 'LibRaw_progress',
  ERRORS: 'LibRaw_errors',
  THUMBNAIL_FORMATS: 'LibRaw_thumbnail_formats',
  INTERNAL_THUMBNAIL_FORMATS: 'LibRaw_internal_thumbnail_formats',
  IMAGE_FORMATS: 'LibRaw_image_formats',
};
const enums = { all: ENUMS };
for (const [alias, cEnumName] of Object.entries(ENUM_ALIASES)) {
  enums[alias] = ENUMS[cEnumName];
}

// T13: warningNames(mask) as a plain function alongside the native
// InstanceMethod of the same name (src/addon.cc's WarningNames) -- both are
// exported; this one is documented as the primary entry point since it
// needs no native call (pure JS-side table lookup, scripts/gen-enums.js's
// `namesForMask`) and works identically off-thread/before the addon loads
// any LibRaw instance.
function warningNames(mask) {
  return namesForMask('LibRaw_warnings', mask >>> 0);
}

// T13: capabilityNames() -- LibRaw::capabilities()'s (this module's
// `capabilities()`, re-exported from `native` below) set bits as short
// names (e.g. ['ZLIB', 'JPEG']), via the same generated CAPS table.
function capabilityNames() {
  return namesForMask('LibRaw_runtime_capabilities', native.capabilities() >>> 0);
}

// Node-API's DefineAddon() defines every exported property as
// non-enumerable and non-writable (napi_default attributes), so a plain
// object spread (`{ ...native }`) silently drops all of them -- copy each
// own property descriptor explicitly instead, then override `Processor`
// (the wrapped, LibRawError-throwing version) and add `LibRawError`.
// T13: `capabilityNames`/`warningNames` also exist as native InstanceMethods
// (src/addon.cc, same names) so the addon itself is a complete, table-driven
// surface -- but the public export below is the JS wrapper defined above
// (no native call needed, works the same off the LibRaw-loaded addon), so
// those two keys are skipped here and set explicitly, same pattern as
// `Processor`/`LibRawError` below.
const NATIVE_OVERRIDDEN = new Set(['Processor', 'capabilityNames', 'warningNames']);
const exportsObj = {};
for (const key of Object.getOwnPropertyNames(native)) {
  if (NATIVE_OVERRIDDEN.has(key) || FUSED_METHODS.includes(key)) continue;
  Object.defineProperty(exportsObj, key, Object.getOwnPropertyDescriptor(native, key));
}
Object.defineProperty(exportsObj, 'Processor', { value: Processor, writable: true, enumerable: true, configurable: true });
Object.defineProperty(exportsObj, 'LibRawError', { value: LibRawError, writable: true, enumerable: true, configurable: true });
Object.defineProperty(exportsObj, 'progressStages', { value: NAME_TO_STAGE, writable: true, enumerable: true, configurable: true });
Object.defineProperty(exportsObj, 'enums', { value: enums, writable: true, enumerable: true, configurable: true });
Object.defineProperty(exportsObj, 'capabilityNames', { value: capabilityNames, writable: true, enumerable: true, configurable: true });
Object.defineProperty(exportsObj, 'warningNames', { value: warningNames, writable: true, enumerable: true, configurable: true });
for (const method of FUSED_METHODS) {
  Object.defineProperty(exportsObj, method, { value: fused[method], writable: true, enumerable: true, configurable: true });
}

module.exports = exportsObj;
