// T06: shared LibRaw error-code -> name lookup and two Napi::Error throw
// shapes.
//
// decodeSync (T04) predates the Processor error model and its JS-visible
// error shape (`code` property = the LIBRAW_* name string) is exercised by
// an existing committed test (test/decode-sync.test.ts); ThrowLegacyError
// keeps that exact shape so decodeSync keeps working unmodified, per T06's
// task text ("Keep decodeSync working ... you may refactor it to share the
// new error helper"), while now sourcing names from the generated table
// instead of a hand-written switch.
//
// Processor (T06) uses the shape documented in
// docs/reference/proposed-binding-api.md / the T06 task text: the native
// side throws a plain Napi::Error with numeric `code`, string `librawName`,
// and `stage` properties; lib/processor.cjs wraps that into a LibRawError
// (lib/errors.cjs) whose own `code`/`name`/`stage` fields come from those
// three properties (`name` = `librawName`, matching the LibRaw enumerator).
#pragma once

#include <napi.h>

namespace libraw_node {

// Looks up the LIBRAW_* enumerator name for `code` (enum LibRaw_errors,
// libraw_const.h) via the table generated by scripts/gen-errors.js. Unknown
// codes (should not happen for values LibRaw itself returns) map to
// "LIBRAW_UNSPECIFIED_ERROR".
const char* LibRawErrorName(int code);

// Legacy shape (T04's decodeSync): message is "<stage>: <LibRaw::strerror>",
// `code` property is the LIBRAW_* name string. Always throws.
void ThrowLegacyLibRawError(Napi::Env env, int code, const char* stage);
void CheckLegacyLibRaw(Napi::Env env, int code, const char* stage);

// Processor shape (T06+): message is "<stage>: <LibRaw::strerror>", `code`
// property is the numeric LibRaw error code, `librawName` is the LIBRAW_*
// name string, `stage` is the failing call's name. Always throws.
void ThrowProcessorError(Napi::Env env, int code, const char* stage);
void CheckProcessorError(Napi::Env env, int code, const char* stage);

// T07: same shape as ThrowProcessorError/CheckProcessorError above, but
// *returns* the Napi::Error instead of throwing it. AsyncWorker::OnOK/OnError
// (src/async_workers.h) run on the JS thread but are not called via the
// normal N-API call path that node-addon-api wraps in a try/catch to convert
// a C++ exception into a pending JS exception -- they must hand the error to
// a Napi::Promise::Deferred::Reject() instead, which needs a napi_value, not
// a thrown exception. ThrowProcessorError/CheckProcessorError (used by the
// *Sync methods, where a real C++ throw is correct) are implemented in terms
// of this.
Napi::Error MakeProcessorError(Napi::Env env, int code, const char* stage);

// T07: the busy-guard error. Not a LibRaw error code (LibRaw never returns
// it) -- ERR_LIBRAW_BUSY / -1000001 is this binding's own, documented in
// lib/errors.cjs, for "a Processor async/sync call was made while another
// async call on the same Processor is in flight" (docs/plan/tasks.md T07:
// "Busy guard ... rejects immediately with a LibRawError whose name is
// ERR_LIBRAW_BUSY; sync accessors throw the same while busy").
constexpr int kErrLibRawBusyCode = -1000001;
constexpr const char* kErrLibRawBusyName = "ERR_LIBRAW_BUSY";

Napi::Error MakeBusyError(Napi::Env env, const char* stage);
void ThrowBusyError(Napi::Env env, const char* stage);

// T08: the pre-aborted-signal shape for the fused helpers (decode/thumbnail)
// -- docs/plan/tasks.md's T08 "if signal.aborted is already true at call
// time, reject immediately with a LibRawError name: 'LIBRAW_CANCELLED_BY_
// CALLBACK', code: -100010, aborted: true". Same code LibRaw itself uses for
// LIBRAW_CANCELLED_BY_CALLBACK (see the T09 how-to doc's correction: -100010,
// not -8), so this reuses MakeProcessorError for the message/code/librawName/
// stage shape and only adds the JS-visible `aborted` flag on top. T09 reuses
// this for cancellation *during* a call, not just before it starts.
Napi::Error MakeCancelledError(Napi::Env env, const char* stage);

}  // namespace libraw_node
