// T06: shared LibRaw error-code -> name lookup and two Napi::Error throw
// shapes.
//
// decodeSync (T04) predates the Processor error model and its JS-visible
// error shape (`code` property = the LIBRAW_* name string) is exercised by
// an existing committed test (test/decode-sync.test.ts); ThrowLegacyError
// keeps that exact shape so decodeSync keeps working unmodified, per T06's
// task text ("Keep decodeSync working ... you may refactor it to share the
// new error helper"), while now sourcing names from the generated table
// instead of a hand-written switch.
//
// Processor (T06) uses the shape documented in
// docs/reference/proposed-binding-api.md / the T06 task text: the native
// side throws a plain Napi::Error with numeric `code`, string `librawName`,
// and `stage` properties; lib/processor.cjs wraps that into a LibRawError
// (lib/errors.cjs) whose own `code`/`name`/`stage` fields come from those
// three properties (`name` = `librawName`, matching the LibRaw enumerator).
#pragma once

#include <napi.h>

namespace libraw_node {

// Looks up the LIBRAW_* enumerator name for `code` (enum LibRaw_errors,
// libraw_const.h) via the table generated by scripts/gen-errors.js. Unknown
// codes (should not happen for values LibRaw itself returns) map to
// "LIBRAW_UNSPECIFIED_ERROR".
const char* LibRawErrorName(int code);

// Legacy shape (T04's decodeSync): message is "<stage>: <LibRaw::strerror>",
// `code` property is the LIBRAW_* name string. Always throws.
void ThrowLegacyLibRawError(Napi::Env env, int code, const char* stage);
void CheckLegacyLibRaw(Napi::Env env, int code, const char* stage);

// Processor shape (T06+): message is "<stage>: <LibRaw::strerror>", `code`
// property is the numeric LibRaw error code, `librawName` is the LIBRAW_*
// name string, `stage` is the failing call's name. Always throws.
void ThrowProcessorError(Napi::Env env, int code, const char* stage);
void CheckProcessorError(Napi::Env env, int code, const char* stage);

}  // namespace libraw_node
