// T10: LibRaw_progress code -> short-name lookup, generated from
// vendor/LibRaw/libraw/libraw_const.h by scripts/gen-progress.js (mirrors
// src/errors.h/.cc's LibRawErrorName for `enum LibRaw_errors`). Used by
// src/events.h's progress-event recording to turn the numeric `stage`
// LibRaw's progress callback receives into the short name (e.g.
// LIBRAW_PROGRESS_LOAD_RAW -> "LOAD_RAW") the `progress` event's `stage`
// field carries -- see docs/plan/tasks.md's T10 section.
#pragma once

namespace libraw_node {

// Looks up the short name (enumerator name with the "LIBRAW_PROGRESS_"
// prefix stripped) for `stage` (enum LibRaw_progress, libraw_const.h) via
// the table generated by scripts/gen-progress.js. Unknown values (should not
// happen for values LibRaw itself passes to the progress callback) map to
// "UNKNOWN".
const char* ProgressStageName(int stage);

}  // namespace libraw_node
